### PR TITLE
Fix has one issue

### LINKED ISSUE #63: HasOne relationship...
Hello again! Let's say i have two models: 
**Human** and **Brain**
it is one-to-one (**hasOne**) relationship. 

Currently code:models generates 
`	public function brains()
	{
		return $this->hasMany(\App\Brain::class);
	}
`
instead of
`	public function brain()
	{
		return $this->hasOne(\App\Brain::class);
	}
`
in Human model.

Is there any way, i can tell the library to use hasOne instead of hasMany? I didn't find any. I also wanted to make it on my own (and create pull request), but then I looked at the code. It is beautiful. But too complex for me, no matter how hard i tried to understand it :-( . Maybe you can tell direction (location of code to edit) and i can make it?

P.S. Only then, when i've looked at your code, i have really understood, how much work was made by you. Have my big respect.

### PR DESCRIPTION
**Pull request by anurbol**
Fixes #63. There was a problem in isUniqueKey(), also eliminated unnecessary use of bitwise operators (less complexity). Another thing, we should not care about multicolumn UNIQUE keys.

### CODE REVIEW

File: src/Meta/Blueprint.php [hunk 1]
```diff
@@ -260,17 +260,16 @@ public function references(self $table)
...
         foreach ($this->unique as $index) {
-            foreach ($index->columns as $column) {
-                $is &= in_array($column, $constraint->columns);
-            }
-            if ($is) {
-                return true;
+
+            // We only need to consider cases, when UNIQUE KEY is presented by only ONE column
+            if (count($index->columns) === 1 && isset($index->columns[0])) {
+                if (in_array($index->columns[0], $constraint->columns)) {
```
Comment (CristianLlanos) [inline src/Meta/Blueprint.php]: This code only works when the constraint is applied to a single column. However, you can add a UNIQUE KEY constraint that applies to more than one column. I think this is called "compound unique key" or "multiple-column index". How would you solve that?

Comment (anurbol) [reply src/Meta/Blueprint.php]: Well, I left a comment about that, though it may be not so clear. I thought through the problem and decided that in case of one-one relation, we never deal with compound unique keys. 

Let's mention example from the issue (Human-Brain). Can you imagine situation when Brain has compound key made of human_id and (?). Which key can be there instead of the question sign? 

Oh, wait... It can be skull_id... :) 

Give me a time...

Comment (anurbol) [reply src/Meta/Blueprint.php]: Well, even that example with skull_id is somewhat very unrealistic. I propose to merge this as is, my arguments are: 
1) this fixed my problem
2) let's be iterative, small steps are better than no progress
3) if someone needs that strange one-one relation with compound key, then let him think how to solve this too :) 
Or if you have suggestions, lets work this together, though I feel that it would be almost or absolutely useless work. 

What do you think?

Comment (CristianLlanos) [reply src/Meta/Blueprint.php]: I'll merge this for now. However, I might change it before I publish the next release. Thanks for contributing. 👍

Comment (anurbol) [reply src/Meta/Blueprint.php]: Yes, would be cool if you mention me, i am curious what can be done here. Thank for merge! And waiting for release :)
